### ISSUE TITLE
Cannot read SSID password if there's a space between the SSID's name

### ISSUE THREAD

**Issue by engineer22** [sdushantha/wifi-password#11]
If I run **sudo wifi-password** I get

> ERROR: Could not find password

This is because my AP's name has a space inside (e.g: **John DoeWifi**)

If I create a new AP and name it **JohnDoeWifi**, I successfully get the result

> password123

The program doesn't take into consideration that there may be an SSID with space inside the name. Only SSIDs with no space are read.

**Comment by sdushantha** [comment]
Hi @engineer22,

Thank you for bringing up this bug. 

On line 65 if you replace that line with the code below, does it fix the issue?
```python
        password = run_command(f"cat '/etc/NetworkManager/system-connections/{ssid}.nmconnection' | grep psk=")
```

**Comment by engineer22** [comment]
Hello @sdushantha,

I will test in couple hours and get back to you. Thank you.

**Comment by barak** [comment]
I had the same problem and your line 65 patch (adding `'`s) fixed it.

**Comment by theRealStyro** [comment]
I think it would be a good idea to add this to the main branch

**Comment by engineer22** [comment]
Fixed.
