### ISSUE TITLE
Application throws Index out of range error when SSID is not found in Windows

### ISSUE THREAD

**Issue by pelonchasva** [sdushantha/wifi-password#12]
I was trying to use the program without any arguments and it throws an `index out of range exception` because the variable `ssid` is an empty string:

![image](https://user-images.githubusercontent.com/4713147/106071755-24ab6180-60c4-11eb-92e1-4326eead5095.png)

After some debugging the issue is found in the method `get_ssid` when the platform is `win32`, in my case, I don't have wifi enable so that's why the SSID interface is not being fetched, but apparently the `netsh` command returns an empty value and when trying to grab the index of 0, it breaks because there is nothing defined.

* `OS`: Windows 10
* `Python version`: 3.8.1

**Comment by sdushantha** [comment]
Closing this as this issue has been dealt with in #13
