### ISSUE TITLE
Could not find password on Ubuntu

### ISSUE THREAD

**Issue by AlessandroTomella** [sdushantha/wifi-password#17]
Hi awesome work, 
however I noticed on Linux (Ubuntu 18 LTS) throws the error : `ERROR: Cound not find password`. This happens because it looks in **`/etc/NetworkManager/.../`** for files with name `{ssid}.nmconnection`, whereas in my case those files are just named as `{ssid}`. Changing `{ssid}.nmconnection` to  just `{ssid}` solved my issue.

**Comment by sdushantha** [comment]
Thank you for letting me know about this issue. I have temporarily removed support for Linux because there seems to be a lot of problems. As @littlediobolic mentioned in #21:

> Unfortunately network management can vary from device to device making it hard to account for everything. For instance, the Raspberry Pi doesnt even use NetworkManager at all to manager Wifi AFAIK
