### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by dhergert** [sdushantha/wifi-password#32]
Can the steps to uninstall be documented on the README, or better yet, automated?  Adding an uninstall flag to the setup.py would be optimal.

Looking at the install logs, is this essentially it?

```
rm /usr/local/bin/wifi-password
rm /usr/local/lib/python3.9/site-packages/wifi_password-*.egg
```

**Comment by sdushantha** [comment]
Hi @dhergert,

You should be able to uninstall `wifi-password` by running `python3 -m pip uninstall wifi-password`.

Let me know how that goes 😊
