### ISSUE TITLE
-i and --image don't work?

### ISSUE THREAD

**Issue by OmgImAlexis** [sdushantha/wifi-password#34]
Neither `-i` nor `--image` returns an image. Instead I see the password in plain text.

I'm on commit 1cc6ba2deac3855de32108fca0aa4db99371dc56. I'm using macOS 10.15.7 and the built in terminal.

**Comment by sdushantha** [comment]
Hi @OmgImAlexis,

It looks like you have misunderstood how to use the `--image` flag. In the description for the `--help` flag, it states that it

> must be used along with --qrcode

I understand that this syntax may be confusing as the flags are not that intuitive. We therefore working on making it better in #22 based on this comment https://github.com/sdushantha/wifi-password/pull/22#issuecomment-770908185, where the syntax will look like this:

- `--show-qr`: show qr code on the commandline
- `--save-qr image.png`: save qr code into image file `path`
- ``: do neither.
- `--show-qr --save-qr image.png`: do both
