### ISSUE TITLE
I'll try to move into `common-cxxflags.py` and let you know.

### ISSUE THREAD

**Issue by Co0olboi** [sdushantha/wifi-password#48]
I'll try to move into `common-cxxflags.py` and let you know.

- [x] __Originally posted by @X-Ryl669 in https://github.com/MarlinFirmware/Marlin/pull/21051#discussion_r575244911__

**Comment by sdushantha** [comment]
Hey @Co0olboi,

I think you might have created the issue on the wrong repo because what you have written is not related to this project.

Closing this.
