### ISSUE TITLE
'netsh' command does not work for `WPA2-Enterprise` 

### ISSUE THREAD

**Issue by xiangmingzhe0928** [sdushantha/wifi-password#52]
Hi It's a great project!:two_hearts:

i found the `Key Content(password ) `is not displayed  when the types of networks is `WPA2-Enterprise` 

---
- e.g
```
Security settings
-----------------
    Authentication         : WPA2-Enterprise
    Cipher                 : CCMP
    Authentication         : WPA2-Enterprise
    Cipher                 : GCMP
    Security key           : Absent
    802.1X                 : Enabled
    EAP type               : Microsoft: Protected EAP (PEAP)
    802.1X auth credential : User credential
    Credentials configured : No
    Cache user information : Yes
```

Is there a way to solve this situation?
Thx~~~~

**Comment by sdushantha** [comment]
@xiangmingzhe0928 The password cannot be found if you are on an enterprise network. I tried it on my enterprise network and failed to retrieve the Wifi password. If I remember correctly, it is because the password is encrypted.
