### ISSUE TITLE
zsh: command not found: wifi_password

### ISSUE THREAD

**Issue by lihuacai168** [sdushantha/wifi-password#57]
It isn't work at `wifi_password` 
```
#  rikasai @ huacainoMBP in ~ [22:27:59]
$ wifi_password
zsh: command not found: wifi_password
```
But work at `python -m wifi_password`
```
# rikasai @ huacainoMBP in ~ [22:27:30]
$ python -m wifi_password
*********
```
![image](https://user-images.githubusercontent.com/11568297/112852489-92810300-90de-11eb-9528-8959b2359fa7.png)

**Comment by littlediobolic** [comment]
I think it might be `wifi-password`, any luck with that?

**Comment by lihuacai168** [comment]
> I think it might be `wifi-password`, any luck with that?

![image](https://user-images.githubusercontent.com/11568297/113585130-6295aa80-965e-11eb-8678-3d6e87d079b1.png)
 `wifi-password` and ` wifi_password` is neither work.

**Comment by littlediobolic** [comment]
Sorry for the delay, if you check `/usr/bin/` is wifi-password there? Or locate the wifi-password script and make sure it is in your $PATH. You can also check `which wifi-password' to see if that comes up with anything.

**Comment by lihuacai168** [comment]
> Sorry for the delay, if you check `/usr/bin/` is wifi-password there? Or locate the wifi-password script and make sure it is in your $PATH. You can also check `which wifi-password' to see if that comes up with anything.

![image](https://user-images.githubusercontent.com/11568297/115954342-07e7c400-a523-11eb-933f-839c95d66dc9.png)

wifi_password not in my $PATH

**Comment by sdushantha** [comment]
@lihuacai168 It seems like the script location is not in your `PATH` hence, you are unable to execute `wifi-password` from the command line. Since it looks like you are using macOS, add the following line of code to your `.bashrc` or `.zshrc` or whatever config file your shell uses:
```bash
PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.8/bin"
```

Then either restart your terminal or reload the config file and running `wifi-password` should work without an issue.

**Comment by lihuacai168** [comment]
> @lihuacai168 It seems like the script location is not in your `PATH` hence, you are unable to execute `wifi-password` from the command line. Since it looks like you are using macOS, add the following line of code to your `.bashrc` or `.zshrc` or whatever config file your shell uses:
> 
> ```shell
> PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.8/bin"
> ```
> 
> Then either restart your terminal or reload the config file and running `wifi-password` should work without an issue.

I am using pyenv. There isn't  `/Library/Frameworks/Python.framework`
![image](https://user-images.githubusercontent.com/11568297/115962830-b570cc80-a54f-11eb-8daf-dd1b0bac10f5.png)

![image](https://user-images.githubusercontent.com/11568297/115962726-4a26fa80-a54f-11eb-8edb-4fa08ea34190.png)

**Comment by littlediobolic** [comment]
Is the program in /usr/bin? If not youll need to find where it was installed. You can try `find / - type f - name wifi-password` should show you where on the system wifi-password is.

**Comment by lihuacai168** [comment]
> Is the program in /usr/bin? If not youll need to find where it was installed. You can try `find / -type f -name wifi-password` should show you where on the system wifi-password is.

No,I can't find program in `/usr/bin`.
I try `find / -type f -name wifi-password`, but not found `wifi-password`.
When the command has been running for 20 minutes, I terminated it.

**Comment by sdushantha** [comment]
@lihuacai168 Uninstall `wifi-password` using pip. Then reinstall it using pip and show us the command your ran and the full output that pip gave out while installing `wifi-password`.

**Comment by lihuacai168** [comment]
> @lihuacai168 Uninstall `wifi-password` using pip. Then reinstall it using pip and show us the command your ran and the full output that pip gave out while installing `wifi-password`.

I reinstall `wifi-password`, and it works.
![image](https://user-images.githubusercontent.com/11568297/115994767-e530da80-a60a-11eb-891b-322248d84c05.png)

**Comment by sdushantha** [comment]
That's great! In case you want to know, your script location seems to be in `/User/rikasai/.local/bin/`:
![image](https://user-images.githubusercontent.com/27065646/115995071-0e854280-a5da-11eb-9060-e41501045cae.png)
