### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by pengyouyoupeng** [sdushantha/wifi-password#70]
have a error
`-bash:/usr/local/bin/wifi-password :NO such file or directory`

**Comment by pengyouyoupeng** [comment]
I solve:
![383A0EE0AF3BC0D173EFC0BF9E26DE11](https://user-images.githubusercontent.com/18572036/114959389-8a271700-9e97-11eb-9043-e5e6bf5dbe6f.jpg)
`1. which wifi-password`
 /Library/Frameworks/Python.framework/Versions/3.7/bin/wifi-password
`2.sodo mv /Library/Frameworks/Python.framework/Versions/3.7/bin/wifi-password /usr/local/bin/wifi-password`
it works

**Comment by sdushantha** [comment]
This is an issue with your enviornment and not `wifi-password`.
