### ISSUE TITLE
wifi-password is not recognized

### ISSUE THREAD

**Issue by ShimmerSummer** [sdushantha/wifi-password#75]
it showed
wifi-password is not recognized as an internal or external command, operable program or batch file.
even after i installed wifi-password using pip on windows10 system.

**Comment by sdushantha** [comment]
Hi @ShimmerSummer,

This is an issue with your environment and not `wifi-password`. It seems like you have not added Python's scripts directory to the PATH. Try reading this StackOverflow answer: https://stackoverflow.com/a/23709194/9215267

If it doesn't work, try Googling "how to add python scripts directory to path" or something along those lines.
