### ISSUE TITLE
Do I have to enter my wifi password somewhere?

### ISSUE THREAD

**Issue by Fr-gs** [sdushantha/wifi-password#76]
This might be a stupid question but do I have to enter my wifi password I'm scanning the qr code given but it my phone doesn't log in. If I do have to enter a password where? Thank you

**Comment by sdushantha** [comment]
I think this might be an issue with your phone. What I do is that I use the inbuilt QR code reader in my Camera app and scan the QR code. I then get a pop-up asking me if I want to join the WiFi network associated with the information in the QR code. When I tap yes, I automatically get connected. So do not need to type any password on my phone.

The image below shows how my phone tends to work:
![image](https://user-images.githubusercontent.com/27065646/127777432-40e2c48e-a912-44cb-8839-1499fe390b65.png)
